//Application=name
spring.application.name=meal

//PostgreSQL=connection - Host: localhost; Port: 5432; Database: meals; pgUserName: ; pgPassword:
spring.datasource.url=jdbc:postgresql://localhost:5432/meals
spring.datasource.username=postgres
spring.datasource.password=postgres

//Hibernate=automatically updates the database schema based on Entities
spring.jpa.hibernate.ddl-auto=update

//Shows=generated SQL in the console. Useful for learning JPA/Hibernate.
spring.jpa.show-sql=true

//Disables=Open Session in View
spring.jpa.open-in-view=false

//=runs on: localhost:8081
server.port=8081